CREATE TABLE `crac_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned NOT NULL,
  `year` int NOT NULL DEFAULT '0',
  `continent` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `cn_region_code` int NOT NULL DEFAULT '0' COMMENT '中国行政区代码，区分省份',
  `cn_by_code` tinyint NOT NULL DEFAULT '-1' COMMENT '呼号归属by区域0-9',
  `call_obj` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `mode` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `band` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `qso_date` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `time_on` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `time_off` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `qso_timestamp` int NOT NULL DEFAULT '0',
  `frequency` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `station_callsign` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `operator` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `log_file` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status` tinyint NOT NULL DEFAULT '0',
  `created_time` int NOT NULL DEFAULT '0',
  `update_time` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `crac_log_user_id_index` (`user_id`),
  KEY `crac_log_mode_index` (`mode`),
  KEY `crac_log_band_index` (`band`),
  KEY `crac_log_qso_date_index` (`qso_date`),
  KEY `crac_log_time_on_index` (`time_on`),
  KEY `crac_log_time_off_index` (`time_off`),
  KEY `crac_log_station_callsign_index` (`station_callsign`),
  KEY `crac_log_call_obj_index` (`call_obj`,`status`) USING BTREE,
  KEY `crac_log_status_index` (`status`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci